#! /usr/bin/env escript

main([]) ->
    {ok, [{shebang,_}, {comment,_}, {emu_args,_},
          {archive, RebarArch}]} = escript:extract("./rebar",[]),
    {ok, RebarFileList} = zip:extract(RebarArch,[memory]),
    {ok, [Shebang, Comment, EmuArgs,
          {archive, AgnerArch}]} = escript:extract("./agner",[]),
    {ok, AgnerFileList} = zip:extract(AgnerArch,[memory]),
    {ok, {_, Arch}} = zip:create("agner",lists:ukeysort(1,AgnerFileList ++ RebarFileList),[memory]),
  escript:create("agner", [Shebang, Comment, EmuArgs, {archive, Arch}]).

